name: CraftedKingdoms
version: 1.0.0
main: com.technovision.craftedkingdoms.CraftedKingdoms
api-version: '1.20'
commands:
  group:
    description: Manage your groups
    usage: /group
    aliases: [g]
  fortify:
    description: Protect blocks for your groups
    usage: /fortify
    aliases: [f]
  soulshard:
    description: Manage your soul shards
    usage: /soulshard
    aliases: [shard, ss]
  groupchat:
    description: Switch chat groups
    usage: /groupchat
    aliases: [gc, chat, c]
  snitch:
    description: Manage your group snitches
    usage: /snitch
  recipes:
    description: View custom crafting recipes
    usage: /recipes
    aliases: [crafting]
  crops:
    description: View crops that can grow in this biome
    usage: /crops
    aliases: [farming]
  map:
    description: Get link to server map page
    usage: /map